galaga: main.o functions.o
	g++ -Wall main.o functions.o -o galaga -lsfml-graphics -lsfml-windo
main.o: main.cpp
	g++ -Wall -c main.cpp
functions.o: functions.h functions.cpp
	g++ -Wall -c functions.h functions.cpp
